### ISSUE TITLE
Less/No Manipulation

### ISSUE THREAD

**Issue by pumatertion** [kenjis/php-framework-benchmark#10]
Any kind of framework should use its default "out of the box" features/behaviour. Symfony f.e. should be the result of: "composer create-project symfony/framework-standard-edition" using the same AppKernel settings from the demo acme bundle. Something like this is to much manipulation: https://github.com/kenjis/php-framework-benchmark/pull/3/files#diff-916370cff7f64fa71f0e69c922b515aaL17

Setups should follow the frameworks documentation to run a sample application or base distribution, imho.

TYPO3 Flow Benchmark f.e. using its default setup without any further patching and optimizations. It's what the user gets by following the documentation. Except a package wich provides simple basic settings and does not optimize anything to get better performance: https://github.com/pumatertion/typo3.benchmark

**Comment by harikt** [comment]
I agree with you :) .

**Comment by kenjis** [comment]
Thank you for your opinion.

After my consideration, I agree with you. And I reverted optimization for Symfony 2.6.
It was only optimized.

See https://github.com/kenjis/php-framework-benchmark#benchmarking-policy

And I updated the results: https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

**Comment by pumatertion** [comment]
Thank you for this!!
