### ISSUE TITLE
Keep link to your blog

### ISSUE THREAD

**Issue by harikt** [kenjis/php-framework-benchmark#11]
Hi, 

It will be nice if you can link to the blog posts of each experiments.

Thank you

**Comment by kenjis** [comment]
That post is a bit out of dated now. Framework versions and application code/configuration are changing little by little. So I think comparision of each experiments is not useful so much.

So I added a note in the blog post.

> This article is out of dated. Please see the latest benchmarks at <https://github.com/kenjis/php-framework-benchmark>. I've changed my benchmarking policy, the number of frameworks to benchmark has been increased, and version of frameworks has been updated.

For the time being I will not update the post or post new blog post about this benchmarks. But thank you for your comment.
