### ISSUE TITLE
Phalcon 2

### ISSUE THREAD

**Issue by Green-Cat** [kenjis/php-framework-benchmark#12]
Could you please add benchmarks for phalcon 2?

**Comment by kenjis** [comment]
According to my benchmarks, phalcon 2 is as fast as 1. There is no big difference.
And there is another benchmarks: http://blog.ohgaki.net/phalcon-1-3-2-0-benchmark

But if you really care about the difference to you, I encourage you to benchmark on your own environment.

Phalcon 2 is going to come soon. So I changed 1.3 to 2.0.0-rc.
