### ISSUE TITLE
Why my Lumen is so much slower than Taylor's?

### ISSUE THREAD

**Issue by kenjis** [kenjis/php-framework-benchmark#13]
According to http://taylorotwell.com/how-lumen-is-benchmarked/ :

| framework | requests per second |
| --- | --: |
| Slim 2 | 1700-1800 |
| Lumen | 1800-1900 |
| Slim 3 | 1200-1300 |
- Lumen is a bit faster than Slim2.

But my benchmarks (2015/04/15) :

| framework | requests per second |
| --- | --: |
| slim-2.6 | 774.31 |
| lumen-5.0 | 372.07 |
- Slim2 is about two times faster than Lumen.

I've found some differences in code, but overall benchmarking methodology seems to be the same.

> don’t be surprised if your numbers are different than my numbers.

Yes, benchmarking environments change numbers. But the difference (relatively to Slim2) is too much, isn't it?

I simply want to know why. What makes the huge difference?

**Comment by kenjis** [comment]
My VM had small memory, so I changed it to 2GB.

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|slim-2.6           |             827.37|    18.4|       0.50|     1.0|
|yii-2.0            |             413.81|     9.2|       1.75|     3.5|
|silex-1.2          |             364.08|     8.1|       1.00|     2.0|
|lumen-5.0          |             381.07|     8.5|       1.00|     2.0|

But still slim2 is much faster.

**Comment by neomerx** [comment]
@kenjis
* kernel settings
* PHP engine
* testing script & the way you use ab

When I [researched Laravel](https://github.com/neomerx/rhw-l5) I started with the same kernel settings as you. However I found out I had performance results degraded rapidly after each ab run and therefore were totally unreliable. I'm not saying I changed them to best possible but I did have more stable results.

Taylor didn't disclosed what PHP engine used but most likely he had chosen HHVM for the reason it better optimizes Laravel/Lumen than it's competitors (that's from my experience). I think mostly for 'code inlining' feature.

Try testing only a few frameworks at the same time (e.g. slim vs lumen only) and run them *manually* with delays and *more than one time*. That's my numbers how Laravel reacts on few ab runs **374.73**, 682.83, 584.68, **771.33**, 729.74, 734.95 RPS.

**Comment by samdark** [comment]
So, questions:

1. Which engine was used? HHVM or Zend PHP?
2. Which version of engine?
3. Which PHP settings?
4. Was APC/OpCache used?

**Comment by samdark** [comment]
Also, `ab` isn't really good way to test. `sigege` is much better.

**Comment by barryvdh** [comment]
I think Taylor said that he didn't test with HHVM, and he used Homstead (Vagrant):
http://laravel.com/docs/5.0/homestead#included-software
So Nginx + php5.6.

Maybe try running the benchmarks from within Homestead?

**Comment by neomerx** [comment]
@barryvdh As I understand it Homestead is just Ubuntu + VirtualBox. Thus adding HHVM to it is just running in terminal

```sudo apt-get install software-properties-common && sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449 && sudo add-apt-repository 'deb http://dl.hhvm.com/ubuntu trusty main' && sudo apt-get update && sudo apt-get install hhvm && sudo service nginx restart```

**Comment by samdark** [comment]
Then it depends very much on which OS is running Vagrant, which VM (WMWare, Virtualbox) and what CPU runs it. In my experience such VM-tests were too far from being accurate so I was setting up a clean 10$ box at DigitalOcean.

**Comment by harikt** [comment]
@samdark +1 for using DO :) .

**Comment by kenjis** [comment]
@samdark 

My environment:

* CentOS 6.5 64bit (VM)
  * PHP 5.5.23 (remi RPM)
    * Zend OPcache v7.0.4-dev
  * Apache 2.2

`php.ini` is probably default of remi.

> such VM-tests were too far from being accurate 

Yes, comparing to your real production environment. And I encourage all of you run benchmarks on your environment for your purpose.

But do relative numbers change so big? In VM, A is twice faster than B, but at DigitalOcean A is as fast as B. Could it be? I don't know.

**Comment by FractalizeR** [comment]
@kenjis  I think it's worth to publish this configuration (OS + PHP) in README so that people know what php version and opcache were used. 

Also PHP 5.5 will enter EOL on 20 Jun. May be we should move to 5.6 in tests?

It would be also interesting to benchmark using HHVM.

**Comment by kenjis** [comment]
@neomerx  @barryvdh Thank you for your comments.

First I'll try Homstead later. It may give me some clues.

**Comment by FractalizeR** [comment]
I think also, that tests must be done in a real OS, not in the VM. For example, VirtualBox at my MacOS (Intel Core i7 2.4GHz, 8Gb RAM) with Laravel gives me page rendering time at about 600ms. That is partly because of slow vbox virtual file system.

**Comment by neomerx** [comment]
@FractalizeR What about moving to SSD from floppy? Kidding you )

**Comment by fesor** [comment]
@FractalizeR, VirtualBox FS is not so slow. Maybe you trying to run apps stored in `vboxsf` shared directory?

**Comment by samdark** [comment]
> But do relative numbers change so big? In VM, A is twice faster than B, but at DigitalOcean A is as fast as B. Could it be? I don't know.

Yes. That's what I was experiening while testing Yii 2.0 HHVM vs PHP 5.6. In my case on VM HHVM was *slower* than Zend Engine.

**Comment by barryvdh** [comment]
Yeah but relatively speaking, if framework A is 2x as fast as framework B, it should probably provide the same relative results in other tests, unless there are major differences in disk i/o, cpu intensive tasks, memory exhaustion or different bottlenecks.

It would be interesting to see what those differences would be, so the frameworks could be optimised perhaps.

**Comment by samdark** [comment]
Correct. VM *could* be such bottleneck.

**Comment by harikt** [comment]
If anyone need to make the fastest micro framework, you MUST use FastRoute for routing. Nothing else can break it ;) . The performance gain is mostly on routing.

**Comment by FractalizeR** [comment]
> VirtualBox FS is not so slow. Maybe you trying to run apps stored in shared directory (vboxsf is terribly slow)?

@fesor Yep, that's exactly what I do. `vboxsf` is terribly, terribly slow.

**Comment by neomerx** [comment]
@harikt I like the idea of having different implementations for routing and nikic without any doubts is a brilliant developer however Laravel and Lumen have exactly the same routing system with drastic performance difference. So other parts of the system are the biggest problems. You probably get some gain for many routes with FastRoute but how many routes there are in default applications? 1-3. I wouldn't expect much of using it in this race.

**Comment by barryvdh** [comment]
@neomerx Lumen is using nikic/fast-route, Laravel is using Symfony routing.

**Comment by barryvdh** [comment]
See this thread for more detailed info by Taylor:
http://www.reddit.com/r/PHP/comments/32kajb/lumen_php_microframework_by_laravel/

**Comment by neomerx** [comment]
@barryvdh Right. I meant piping actually.

**Comment by neomerx** [comment]
I suggested Taylor using FastRoute for L5 and it's good to see it's finally there )

**Comment by harikt** [comment]
@neomerx FastRoute miss some of the good things like domain routing of symfony. So fast doesn't means featured. We may need to use the right router to do the work.

**Comment by neomerx** [comment]
@harikt FastRoute is about implementing this interface
```php
interface Dispatcher {
    const NOT_FOUND = 0;
    const FOUND = 1;
    const METHOD_NOT_ALLOWED = 2;
    /**
     * Dispatches against the provided HTTP method verb and URI.
     *
     * Returns array with one of the following formats:
     *
     *     [self::NOT_FOUND]
     *     [self::METHOD_NOT_ALLOWED, ['GET', 'OTHER_ALLOWED_METHODS']]
     *     [self::FOUND, $handler, ['varName' => 'value', ...]]
     *
     * @param string $httpMethod
     * @param string $uri
     *
     * @return array
     */
    public function dispatch($httpMethod, $uri);
}
```

You're free to support whatever you want

**Comment by seyfer** [comment]
Some answers here
http://stackoverflow.com/questions/29647960/difference-and-similarities-between-lumen-and-laravel/29648574#29648574

http://taylorotwell.com/how-lumen-is-benchmarked/

**Comment by kenjis** [comment]
@FractalizeR I added.
https://github.com/kenjis/php-framework-benchmark#benchmarking-environment

**Comment by FractalizeR** [comment]
@kenjis Great, thanks.

**Comment by fesor** [comment]
Is it possible to create Docker container for every example? I think this would be match better to support.

Also, maybe we should warmup opcache/app caches with preflight request right before run `ab`?

**Comment by FractalizeR** [comment]
I am not sure we need docker here, but I definitely second opcache warmup.

**Comment by harikt** [comment]
@neomerx agree you can implement yourself. Then may need to benchmark with that featured version.

**Comment by koriym** [comment]
FYI @kenjis Here's another great showcase how to benchmark helloworld app.
https://github.com/pmjones/php-framework-benchmarks

**Comment by christoferd** [comment]
Benchmarking hello-world app should be "just for fun", I would not rely on
those numbers to help me make choices.

Laravel will slow down a lot after growing your code with; ORM, ORM helper
magic methods, and Blade

ORM - a lot of stuff is automated, they use string parsing to work out
stuff for you, including pluralisation

ORM magic - again, automated stuff to make your life easier, ++ string
parsing

Blade - string parsing!

What you will need is knowledge on how to speed it up; Cache, fast HDD, a
lot of RAM, etc.

Benchmarking should be done after first load, where a raw first load
benchmark is useless, as after cache kicks in the numbers are much
different. Artisan Optimize also changes a lot.

IMO Laravel = Convenience, if you are looking for speed, look at different
frameworks like phalcon. I believe Laravel allows us to code projects
quicker. IMO any/most project can start with Laravel, small medium business
that affords it can also afford a rebuild later in future as they scale up,
where that rebuild may be in another framework to suit the newer
requirements.

PS: I would love to know how a very large Laravel application with
thousands of users can survive on a server? how fast does it run at peak
use? and how that server is decked out? That would be interesting and
educational.


All the best,

Chris | RandomCodes.com
Product & Services Manager

Ph: +61 (0) 3 5294 0297 | Mob: +61 (0) 419 571 596 | Skype: chris.dedavid
RandomCodes.com <http://randomcodes.com/> | Quality Features
<http://randomcodes.com/doc/?doc=Quality_Features&ref=email_sig> | Order
Document <http://randomcodes.com/doc/?doc=Order_Form&ref=email_sig>
      ...at your service.

.-. .- -. -.. --- -- -.-. --- -.. . ... .-.-.- -.-. --- --

**Comment by plakhin** [comment]
I guess the reason is @taylorotwell has SSD (and uses MacOS as host os) and @kenjis has HDD (and uses other OS as host).

**Comment by Ardakilic** [comment]
@plakhin Taylor uses Virtualbox + Vagrant + Homestead, which is a Linux virtual machine. Even though, the relative results should not differ that much.

**Comment by christoferd** [comment]
@Arda Most Mac machines have SSD or they have HDD in RAID and operate
faster than average non Mac PC.

The HDD setup would make a big difference. Eg. I have 3 x 80mb per second
drives in RAID 0.... I get 240mb/p/s throughput. That's much faster than
average.

My other RAID is SSD and runs over 400mbps. So, I could run benchmark using
"Virtualbox + Vagrant + Homestead" and get different results.

PS: Garbage collection settings would also affect things sometimes, should
turn it off in benchmarks. Or better yet, run the tests many times to get
an average result.


- Chris

**Comment by plakhin** [comment]
@Ardakilic I mentioned MacOS as a HOST OS, which works directly with disk drive.
I'm sure you get very different results testing drive i/o performance even in the same virtual environment and nearly same disk drive but on MacOS vs Linux vs Windows as a host OS.

**Comment by Ardakilic** [comment]
@christoferd Indeed, but would that change the "relative results" ?

**Comment by kenjis** [comment]
Homestead (Vagrant):

* Ubuntu 14.10
  * PHP 5.6.7
    * Zend OPcache v7.0.4-dev
  * Nginx 1.6.2

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|slim-2.6           |             966.62|     2.3|       0.50|     0.0|
|silex-1.2          |             424.03|     1.0|       0.00|     0.0|
|lumen-5.0          |             463.34|     1.1|       0.00|     0.0|

I don't know why but silex and lumen do not output memory usage:
https://github.com/kenjis/php-framework-benchmark/blob/master/lumen-5.0/public/index.php#L30

Note to Homestead setup:
I installed `ab` command and `php-intl` after `vagrant up`. And I changed Nginx config a bit to work my code. I disabled `xdebug`.

```
server {
    listen 80;
    server_name homestead.app;
    root "/home/vagrant/public";

    index index.html index.htm index.php;

    charset utf-8;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/homestead.app-error.log error;

    sendfile off;

    client_max_body_size 100m;

     location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by kenjis** [comment]
My Host is MBA 2013, 1.3GHz Intel Core i5, SSD 128GB, Mac OS X 10.10.3.

**Comment by plakhin** [comment]
@Ardakilic The answer is obvious, Lumen uses disk drive much more (I don't think that's good, but we are not talking about it at this time) so it's results are depends on disk system much more.

**Comment by plakhin** [comment]
@kenjis 128 GB SSD is twice slower than 256 GB in same 2013 MBA and ~4 times slower than in MBPro.

Can anyone run the test on MB PRO or at least on 256 GB MBA 2013-2105 ?

**Comment by kenjis** [comment]
```
vagrant@homestead:~$ sudo hdparm -t /dev/mapper/vagrant--vg-root

/dev/mapper/vagrant--vg-root:
 Timing buffered disk reads: 1068 MB in  3.00 seconds = 355.88 MB/sec
vagrant@homestead:~$ sudo hdparm -t /dev/mapper/vagrant--vg-root

/dev/mapper/vagrant--vg-root:
 Timing buffered disk reads: 1094 MB in  3.01 seconds = 364.01 MB/sec
vagrant@homestead:~$ sudo hdparm -t /dev/mapper/vagrant--vg-root

/dev/mapper/vagrant--vg-root:
 Timing buffered disk reads: 1104 MB in  3.00 seconds = 367.47 MB/sec
```

**Comment by kenjis** [comment]
For your information.

My benchmarking environment (VirtualBox; CentOS 6.5):

```
[vagrant@localhost ~]$ sudo hdparm -t /dev/mapper/VolGroup-lv_root

/dev/mapper/VolGroup-lv_root:
 Timing buffered disk reads: 706 MB in  3.00 seconds = 235.26 MB/sec
[vagrant@localhost ~]$ sudo hdparm -t /dev/mapper/VolGroup-lv_root

/dev/mapper/VolGroup-lv_root:
 Timing buffered disk reads: 708 MB in  3.00 seconds = 235.84 MB/sec
[vagrant@localhost ~]$ sudo hdparm -t /dev/mapper/VolGroup-lv_root

/dev/mapper/VolGroup-lv_root:
 Timing buffered disk reads: 692 MB in  3.00 seconds = 230.52 MB/sec
```

**Comment by neomerx** [comment]
Maybe mount Lumen folder to RAM and mitigate HDD/SSD influence? How big this folder, 20Mb?
```
# fstab
tmpfs /path/to/lumen tmpfs defaults,noexec,nosuid 0 0
```

**Comment by zandzpider** [comment]
Ran tests on Macbook Pro mid 2014
2.2Ghz i7
16GB ram
250 GB SSD on PCI-Express bus

php --version
PHP 5.6.7 (cli) (built: Apr 21 2015 10:06:35)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

curl -IL http://127.0.0.1:80
HTTP/1.1 200 OK
Server: nginx/1.6.3

ab -t 10 -c 10  http://lumen.app/

Requests per second:    645.35 [#/sec] (mean)

**Comment by barryvdh** [comment]
@zandzpider it's not about the RPS in absolute value, but relative to the other frameworks.

**Comment by defenestrator** [comment]
I am fascinated by these performance discussions about web frameworks, especially PHP frameworks. In the real world too much of the internet is beyond our control, so all these suppositions and assertions inevitably fail when released into the wild. 

**I' wonder how many of those in this discussion will ever build something that requires scalability beyond what any of the above-mentioned frameworks are capable of. ** There is probably at least one here who has worked at that scale in an engineering capacity. If that person was asked how they solvedsš that problem, I'm going to go out on a limb and say the answer was not "PHP." This is not to imply that I don't like PHP, I love it, but I love it for its strengths, and despite its faults.

If you need extreme high-speed, web-scale, non-blocking, deeply concurrent, fault-tolerant, highly portable rock-star tech, then PHP is not a great solution. In the event you really need something like that; Go learn Go. (Er learn Erlang.) Heck you could get into NodeJS and see improved performance over PHP. sdIf one's project needs to scale to the size of Twitter, for instance, then you have a good and fortunate problem to solve! But until then this is all intellectual wanking. I'm not trying to piddle on the parade, I just want to keep that fact in focus. There are better languages if you're a speed demon.

**Comment by samdark** [comment]
PHP scales well horizontally because of share-nothing nature. Look at the projects made with it: Yahoo, Facebook, Wikipedia, Flickr, Digg, SourceForge, VK.com, mailchimp etc.

**Comment by FractalizeR** [comment]
@defenestrator 
> If you need extreme high-speed, web-scale, non-blocking, deeply concurrent, fault-tolerant, highly portable rock-star tech

You mean like Facebook and Wikipedia, right? :)

**Comment by neomerx** [comment]
@defenestrator If you do not have passion/time/whatever for optimizing applications it's not the reason to call those who have 'intellectual wankers'.

**Comment by defenestrator** [comment]
I am clearly misunderstood, in this case, I apologize. I'm the first to call my self an avid intellectual wanker, for the record, that's not a judgment from me. Facebook is hardly vanilla PHP. Fractalizer, the sentence you quoted is a little joke; https://www.youtube.com/watch?v=bzkRVzciAZg

**Comment by samdark** [comment]
@defenestrator PHP 7 is going to be as fast as HHVM (which, in its behavior, is compatible with Zend PHP). Yahoo uses vanilla one, others most probably do as well. PHP is, in fact, performant compared to many other interpreted languages.

**Comment by christoferd** [comment]
FYI - Recently installed a php crm on Digital Ocean the cloud server, it
uses SSD, and install APC (~Zend Opcache).
It's very fast, much faster than a shared hosting server. New pages loading
in less than 1 second.
Thought I'd share this as it may help you get more speed from app without
having to change frameworks.

PS: Facebook have a developer blog, they release a lot of awesome insider
dev info. Right, they don't use only vanilla php, a lot of their code is
converted to straight C/C++ and turned into DLL php extension libraries.
That way the library code is static, loaded once, and runs super fast. (*don't
quote me*, it's something like that, find the exact info on their blog) I
believe the Phalcon framework <http://phalconphp.com> does something like
this also.

- Chris

**Comment by kenjis** [comment]
Lumen 5.1 got performance improvement than 5.0:

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|lumen-5.1          |             420.06|     1.2|       1.00|     1.0|
|lumen-5.0          |             349.87|     1.0|       1.25|     1.3|

And slim, lumen and sliex:

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|slim-3.0           |             555.19|     1.6|       0.75|     1.0|
|lumen-5.1          |             427.53|     1.2|       1.00|     1.3|
|silex-1.3          |             350.83|     1.0|       1.00|     1.3|

**Comment by samdark** [comment]
Hmm... are you sure you haven't updated test environment?

**Comment by kenjis** [comment]
I have updated the VM (CentOS 6) with `yum update`. So CentOS is now version 6.6 and PHP is 5.5.30.

**Comment by koriym** [comment]
+1 for using DO and latest stable version of PHP (5.6)

**Comment by samdark** [comment]
That's why it's faster. Not because of new framework versions.

**Comment by barryvdh** [comment]
Well, if both 5.0 and 5.1 are run on the new versions, 5.1 it's still faster ;)

**Comment by samdark** [comment]
Oh. Old ones are from new environment as well? If yes then I'm wrong about environment and indeed 5.1 imroved in this regard.

**Comment by kenjis** [comment]
@koriym What is DO?

**Comment by kenjis** [comment]
The numbers are the results on exactly the same VM and yesterday. I ran the command like below:

~~~
$ sh benchmark.sh lumen-5.1/ lumen-5.0/
~~~

The difference is very big. So 5.1 is apparently faster than 5.0.

**Comment by samdark** [comment]
@kenjis DO means [DigitalOcean](https://www.digitalocean.com/).

**Comment by samdark** [comment]
OK. I just thought 5.0 numbers are from old run.

**Comment by OzanKurt** [comment]
So at the end is it real that slim is faster than lumen?

**Comment by trentramseyer** [comment]
9 times out of 10, yes Slim will be faster.  Especially if you are building an app that other people would consume on their boxes, because every "speed test" defending Laravel and/or Lumen has discussion like this on how exactly you have to set up a box to make it comparable.

**Comment by OzanKurt** [comment]
Thanks a lot for the information. :)

**Comment by Hammad51** [comment]
here is mine, have a look at screenshot.. it's lumen 
![screenshot from 2015-12-23 01 13 56](https://cloud.githubusercontent.com/assets/5514160/11965166/a9138672-a914-11e5-9579-86e80c964e14.png)

**Comment by mruz** [comment]
@kenjis look at my benchmark on the new real machine https://github.com/ice/framework/issues/95#issuecomment-204328130.

**Comment by neomerx** [comment]
@mruz You got 148 RPS but @kenjis got 427.53. And you call it 'new real machine'? Sorry you were sold crap :trollface: /s

**Comment by mruz** [comment]
@neomerx, @kenjis uses OPcache, but I don't.
> There is no special settings/optimizations to boost performance of some frameworks and no cache!

**Comment by neomerx** [comment]
@mruz You will understand what you are doing when someone would cook numbers in favor of Phalcon against your Ice.

**Comment by fesor** [comment]
@mruz why don't you use OPcache? I don't know any "real" production machine which doesn't have opcache (php5.5+). It doesn't related to framework itself, just to php.

The only reason to not use opcache - to make Phalcon  looks better.

> Never trust a benchmark you didn't fake yourself.

**Comment by neomerx** [comment]
> The only reason to not use opcache - to make Phalcon looks better.

Cmon @fesor he is an honest men. His 'new real machine' just didn't have enough disk space :laughing:

**Comment by mruz** [comment]
> It doesn't related to framework itself, just to php.

> The only reason to not use opcache - to make Phalcon looks better.

You said that OPcache doesn't related to framework, so is it to make non Phalcon looks better?

**Comment by cebe** [comment]
@mruz to gain more insight on the effects I suggest you try it. I'd like to see how it changes things.

**Comment by mruz** [comment]
@cebe ok, I'll run it when I get back from work.

**Comment by mruz** [comment]
![screencapture-localhost-php-framework-benchmark-1459598399280](https://cloud.githubusercontent.com/assets/2629882/14226197/3d5b5f1a-f8db-11e5-81db-b16e87a2924f.png)
