### ISSUE TITLE
Laravel-5.0 benchmark is incorrect

### ISSUE THREAD

**Issue by SCIF** [kenjis/php-framework-benchmark#14]
Laravel sets crypted cookie on each request — therefore it so slowly. You must disable it. Or enable auth layer in other frameworks, but it some other kind of tests (very usefull though)

**Comment by ncsft** [comment]
Also in .env
APP_DEBUG=true
This is not production option!

**Comment by kenjis** [comment]
@SCIF 

Would you please see https://github.com/kenjis/php-framework-benchmark#benchmarking-policy ?
I just use the default configuration. I don't add any code to use cookie to my hello world application.

But I know you have a point. If you want to compare after removing it, please do by yourself. It is your benchmarks.

And I accept removing components which is not used only on `optimize` branch.

**Comment by kenjis** [comment]
@ncsft I have no `.env` in [laravel-5.0](https://github.com/kenjis/php-framework-benchmark/tree/master/laravel-5.0). In my understanding it means production.

```
$ php artisan env
Current application environment: production
```

Is there something wrong with me?
