### ISSUE TITLE
yii 2

### ISSUE THREAD

**Issue by EngRajabi** [kenjis/php-framework-benchmark#19]
how yii2 off cache file ???
yii2 with cache file queckly

**Comment by kenjis** [comment]
What do you mean? I'm sorry I don't get what you say.

**Comment by EngRajabi** [comment]
2 point
1) Yii 2.0.4 update to Yii 2.0.5
2) add to file config/db.php
cache schima with file
<?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname=xdaancom_market',
    'username' => 'xdaancom_market',
    'password' => 'qVct4IXlo',
    'charset' => 'utf8',
    'emulatePrepare' => true,
    'enableSchemaCache' => true,
    'schemaCacheDuration' => 3600*12,
    //'tablePrefix' => 'tbl_'
];
and config/web.php
'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
