### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by sing88** [kenjis/php-framework-benchmark#20]
I have this error:

Warning: Division by zero in /var/www/html/php-framework-benchmark/libs/parse_results.php on line 33

**Comment by kenjis** [comment]
See `output/results.hello_world.log`. It seems your data is broken.

Normal data: https://github.com/kenjis/php-framework-benchmark/blob/master/output/results.hello_world.log

**Comment by sing88** [comment]
this content of results.hello_world.log

phalcon-2.0: 2546.68: </body></html>: </body></html>
ice-1.0: 1567.69: </body></html>: </body></html>
slim-2.6: 1767.52: </body></html>: </body></html>
codeigniter-3.0: 2642.22: </body></html>: </body></html>
lumen-5.0: 2848.80: </body></html>: </body></html>
yii-2.0: 2320.53: </body></html>: </body></html>
silex-1.2: 2817.86: </body></html>: </body></html>
cygnite-1.3: 2199.55: </body></html>: </body></html>
bear-1.0: 1767.56: </body></html>: </body></html>
fuel-1.8-dev: 2211.19: </body></html>: </body></html>
cake-3.0: 2854.04: </body></html>: </body></html>
aura-2.0: 2101.84: </body></html>: </body></html>

**Comment by kenjis** [comment]
It seems you don't install this correctly.

You should configure your web server that you can access this repository as `http://127.0.0.1/php-framework-benchmark/`. Or you have to change:
https://github.com/kenjis/php-framework-benchmark/blob/master/benchmark.sh#L3

**Comment by sing88** [comment]
see:

![screen1](https://cloud.githubusercontent.com/assets/817558/8150692/fffe959a-12b9-11e5-98ed-7b66c4f31843.png)

**Comment by kenjis** [comment]
You must install and setup correctly: https://github.com/kenjis/php-framework-benchmark#how-to-benchmark

It seems `ab` requests to 404 pages. Make sure if you can see hello world page like this:

~~~
Hello World! 1310720:0.005535
~~~

Text only. No html tags.

**Comment by xf3** [comment]
kenjis, could you please provide your server configuration? Out of the box only yii works fine, all the other frameworks return 404/500 errors, I think this is because of missing URL rewriting configurations? With some additions, I could make about 50% of frameworks to work properly, but the others continue to return error pages. Have you added something to .htaccess or nginx.conf or similar files? I'm trying to setup the project on nginx server.

**Comment by kenjis** [comment]
@xf3 I don't use mod_rewrite. If you enable it, some frameworks may retrun errors.

**Comment by xf3** [comment]
@kenjis strange then, as I said, only yii uses to work after running setup script. Probably with Apache situation differs.

**Comment by kenjis** [comment]
My Apache config:
~~~
<VirtualHost *:80>
  DocumentRoot /home/vagrant/public
</VirtualHost>
~~~

**Comment by xf3** [comment]
Thanks, will try to figure out the problem

**Comment by mruz** [comment]
I have similar problem with some frameworks (eg. symfony-2.7, laravel-5.1). 

I see after run in the browser http://benchmark/laravel-5.1/public/index.php/hello/index I see only `Hello World!` without memory usage and time. I see the code after response send() in the `laravel-5.1/public/index.php` is not running:

```
$response->send();

$kernel->terminate($request, $response);

printf(
    "\n%' 8d:%f",
    memory_get_peak_usage(true),
    microtime(true) - $_SERVER['REQUEST_TIME_FLOAT']
);
```

laravel-5.1.output
```
Hello World!
```

results.hello_world.log
```
phalcon-2.0: 4080.87:   524288: 0.000593
ice-1.0: 4368.31:   524288: 0.000746
codeigniter-3.0: 472.66:  1310720: 0.010451
yii-2.0: 292.29:  2883584: 0.016363
symfony-2.7: 76.55: Hello World!: Hello World!
laravel-5.1: 83.63: Hello World!: Hello World!
zf-2.4: 82.66:  6815744: 0.039616

```

Any idea?

**Comment by kenjis** [comment]
You probably use  PHP FPM.
http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-terminate-event

**Comment by mruz** [comment]
Yes, I'm using the latest php-fpm 5.6.14

----- Reply message -----
Od: "kenjis" <notifications@github.com>
Do: "kenjis/php-framework-benchmark" <php-framework-benchmark@noreply.github.com>
DW: "Mariusz Łączak" <mruz@poczta.onet.pl>
Temat: [php-framework-benchmark] Division by zero (#20)
Data: czw., paź 22, 2015 22:46

You probably use  PHP FPM.

http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-terminate-event

&mdash;

**Comment by gsouf** [comment]
@kenjis  it appears that the configuration given in the README  requires to run apache2 with mod_php
