### ISSUE TITLE
Add number of included files

### ISSUE THREAD

**Issue by mruz** [kenjis/php-framework-benchmark#26]
What do you think about adding info about included files?
```php
printf(
    "\n%' 8d:%f:%f",
    memory_get_peak_usage(true),
    microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],
    count(get_included_files())
);
```

**Comment by kenjis** [comment]
Sounds good. The number must be `%d`.

**Comment by kenjis** [comment]
Done: https://github.com/kenjis/php-framework-benchmark/commit/56594fc283ae974289440aeb841f7139d7bdc226

**Comment by mruz** [comment]
Thanks, but if I have different path:
```sh
base="http://benchmark"
```
it can't find the required file. What do you think to add relative path to each fw:

```php
require '../../libs/output_data.php';
```

It could work on cli and url eg. `http://benchmark/ice-1.0/public/index.php?_url=/hello/index`

**Comment by kenjis** [comment]
Please don't remove `php-framework-benchmark` folder.

I want to add exactly the same code for every framework. So I don't use relative path.
