### ISSUE TITLE
Where is ZF1 and ZF2 frameworks?

### ISSUE THREAD

**Issue by seyfer** [kenjis/php-framework-benchmark#4]
Please, add them.

**Comment by aart3k** [comment]
+1

**Comment by kenjis** [comment]
I added ZF 2.4 source code: https://github.com/kenjis/php-framework-benchmark/commits/master/zf-2.4
But I've never used ZF as a framework. Is this okay?

**Comment by kenjis** [comment]
I updated the results: https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

I'm sorry I'm not interested in ZF1.

**Comment by axot** [comment]
Even ZF1 was EOL but there are many companies in Japan are using it, is it possible add ZF1 support?  we want do performance tuning based on these scores. Thank you anyway.

**Comment by seyfer** [comment]
Also ZF3 was released and it's great!

**Comment by seyfer** [comment]
I have added ZF3 config
https://github.com/kenjis/php-framework-benchmark/pull/68

**Comment by kenjis** [comment]
@axot You can fork this repository and add ZF1.
But if you send PR, I would merge it.

**Comment by axot** [comment]
Okay, I will send a PR in a few days

**Comment by seyfer** [comment]
I could add ZF1 to my ZF3 PR #68

**Comment by axot** [comment]
@seyfer I'm appreciate if you cloud add ZF1 !

**Comment by cebe** [comment]
better create a separate PR, its easier to review.

**Comment by kenjis** [comment]
Please don't add ZF1 to the ZF3 PR.

**Comment by seyfer** [comment]
@cebe @kenjis  sorry, I saw your comment too late and have added zf1 to my PR already.

But there almost nothing to review. Only _benchmark folders in zf-3.0 and zf-1.12.
I have checked and tested all configs, it's work fine.

If it still should be separated, how I can do it?

**Comment by seyfer** [comment]
I have stopped pulling and it wasn't added to zf3 PR.

I need to create different branch for ZF1 PR ?

**Comment by seyfer** [comment]
@cebe @kenjis ok, there is separated PR for ZF1
https://github.com/kenjis/php-framework-benchmark/pull/69

**Comment by seyfer** [comment]
Also I have closed #68 to switch PR to zf3 branch from my forked repo. New one for ZF3 is https://github.com/kenjis/php-framework-benchmark/pull/70

**Comment by kenjis** [comment]
@seyfer @axot Hey, #69 has  9,925 files. Is it really okay?

**Comment by axot** [comment]
The full version of ZF1 has almost 10k files...

**Comment by seyfer** [comment]
@kenjis , maybe it would be better to add zf1 files as a zip (or another archive type) and unzip it during setup process?

**Comment by kenjis** [comment]
@seyfer Is there no installation via Composer? If not, the PR is okay.

**Comment by seyfer** [comment]
@kenjis It could be done via Composer, but I need to change some files (like index.php) by hands to provide right path to ZF1 lib, which will be installed in vendor. By default ZF1 project doesn't look into vendor directory.

I will do it and will change my PR.

**Comment by seyfer** [comment]
`du -h --max-depth=1 ./ 
56M	./vendor`

**Comment by seyfer** [comment]
I have replaced previous commit using `git --force` option. Please check if it's ok or I need create new PR.
