### ISSUE TITLE
Adding another framework

### ISSUE THREAD

**Issue by snopboy** [kenjis/php-framework-benchmark#44]
I'm in the process of writing my own micro-framework mainly for learning purposes and to test different functionalities, my goal is to get to the most optimized end product possible.
Although it's really messy at the moment and has barely any functionality (list of functionalities available in my repo), I'd like to know how many requests it could handle per second.
Unfortunately I cannot setup a Linux environment and run the benchmark on my personal computer so I'd really appreciate it if you could add this to your benchmarks and update the repo, my micro-framework is open source and available here:
https://github.com/snopboy/Sporter

Thanks in advance, I really appreciate it.

**Comment by kenjis** [comment]
If you write your framework, you should benchmark on your own (production) environment.
If you use frameworks, you should benchmark on your own (production) environment.

Even though this benchmarks do not work on your environment, you could benchmark on your environment. What you need is `ab` command included in Apache.

**Comment by snopboy** [comment]
@kenjis Yeah I tried that out with the ab.exe included in the apache bin directory, though it kept crashing which is unfortunate.
You don't have to benchmark it, I only thought it could be cool to have it there along the other frameworks and see where it stands compared to the others, although being very basic and in very early stage of development.

**Comment by kenjis** [comment]
@snopboy Then, how about this? https://code.google.com/p/siege-windows/
I have never used it, though.
