### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by TheCelavi** [kenjis/php-framework-benchmark#45]
Hi, I can see that you are still active on this project, thank you for that. 

I have just stumbled upon the Taylor Otwell quote: "Laravel 5.2 currently sitting about 25% faster than Laravel 5.1 (before PHP 7)..." https://twitter.com/taylorotwell/status/674327734252892161.

So I see that you still have Laravel 5.1 in benchmarks. Did you planed to put mentioned statement to a test? :)

Off topic - I have asked you once (I believe) how to buy you a beer for your efforts?

**Comment by kenjis** [comment]
Yes, this project is active. But I don't say when I update the benchmarks.
As you see, I have to update not only Laravel but also Symfony and some other frameworks.

Thank you for your offer. :smile: 
 But I don't drink alcohol. If we meet somewhere, please buy me a cup of tea or something. ;-)
