### ISSUE TITLE
Can you explain what the parameters for the benchmarks are? 

### ISSUE THREAD

**Issue by peshmerge** [kenjis/php-framework-benchmark#55]
First of all thank you very much for making such a great tool to benchmark all the php-frameworks. I have question about the bash script located in _functions.sh 
this  `ab -c 10 -t 3 "$url" > "$ab_log"`
do the actual test. 
It's not clear for me how many request per seconds are sent to the framework. I have read the documentation about **ab** and we should specify the amount of requests with -n. I didn't see that in your benchmarking, correct me if I am wrong, please! :+1: 

Please can you maybe explain what you are doing? I mean how much request or maybe how many concurrent users. 

I have ran the benchmark for Symfony 3.0 and Laravel5.2 and I got the following results. 

![screenshot_3](https://cloud.githubusercontent.com/assets/531558/14923729/0ebf8e3c-0e3f-11e6-89e7-01fdbba1471a.jpg)

What I don't understand what does memory usage here mean? I mean I didn't know how many requests are sent and also what the is relation between theses results. 
For example Symfony could handle 639 rps and has spent 7.879 ms with 2.92 MB memory usage. 214 files were included. 

This is specifications of my laptop where I have done the benchmark. 
![screenshot_3](https://cloud.githubusercontent.com/assets/531558/14923776/6c862d82-0e3f-11e6-8aa8-68f060599a8e.png)

These are the results:
![screencapture-127-0-1-1-php-framework-benchmark-1461243921694](https://cloud.githubusercontent.com/assets/531558/14923786/81d5a2c6-0e3f-11e6-9897-0355e0df318a.png) 
The number beside the framework name is the amount of (rps, mb of ms) I did that because I wanted to make a screenshot for the page. Otherwise you should save it as a html page and hover on it with your mouse to be able to see the amount. 

Here info about the version of apache and php 
![screenshot_1](https://cloud.githubusercontent.com/assets/531558/14923824/bf4cd00c-0e3f-11e6-9895-746f5c56bbf6.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/531558/14923831/c2341028-0e3f-11e6-9101-57ab3e6e5ab7.png)

**Comment by kenjis** [comment]
`ab -c 10 -t 3 "$url" > "$ab_log"` means:
* how many concurrent users? -> 10 users
* how many seconds does ab keep sending requests? -> 3 seconds

*memory usage* means the memory peak usage of the framework application.
See https://github.com/kenjis/php-framework-benchmark/blob/master/libs/output_data.php#L5
It is the result of the PHP's `memory_get_peak_usage()` function.

**Comment by peshmerge** [comment]
Hi thanks for your fast answer. 
But it's yet unclear for me how many requests per seconds do we send. I mean you have omitted the parameter **-n** 

Regards,
Peshmerge

**Comment by kenjis** [comment]
> how many requests per seconds do we send

We don't know. I think `-n` option specifies number of requests, but it is NOT requests per second.

`-n` means how many requests do we send. We do not specify how long will we keep sending.
`-t` means how many seconds do we keep sending

**Comment by peshmerge** [comment]
Thank you very much kenjis :+1: 
You are awesome

**Comment by kenjis** [comment]
You're welcome.
