### ISSUE TITLE
Phalcon benchmarking!

### ISSUE THREAD

**Issue by peshmerge** [kenjis/php-framework-benchmark#56]
Hi Kenjis, 

I have a question about Phalcon Benchmarking. Since we haven't installed the extension of Phalcon and we haven't configured anything on our server, how can then phalcon run? 
If you read the documentation of Phalcon https://docs.phalconphp.com/en/latest/index.html
you know what I mean. 
So my question is Phalcon benchmarking legitimate? Personally I don't know, but when I have tried to open the link of the phalcon-2.0 app that being generated after I run the benchmark, I got an error and I couldn't open the link : http://127.0.0.1/php-framework-benchmark/phalcon-2.0/public/index.php?_url=/hello/index

Thanks,

Peshmerge

**Comment by kenjis** [comment]
Yes, Phalcon does not work if you don't install the extension.
The benchmark you see is just the data of error page.

**Comment by peshmerge** [comment]
Okay! So why we call it then benchmarking?! maybe we can better remove it or give clear info about installing the extension and configuring the framework before benchmarking it!

**Comment by terah** [comment]
Some people (myself included) come here looking at how Phalcon performs against the rest.  So, please keep benchmarking it.

**Comment by peshmerge** [comment]
We call it a benchmark when it runs a real application, not testing any 5xx or 4xx pages. It's up to you to use it, but remember you are just measuring a performance for an error page.

**Comment by terah** [comment]
I think the point is that you should install the phalcon extension if you are interested in the phalcon results.

**Comment by trentramseyer** [comment]
Phalcon is a full framework. Just because they were smart enough to compile it to an extension so it is blazing fast doesn't mean it shouldn't be benchmarked.

**Comment by peshmerge** [comment]
I am not saying it shouldn't be benchmarked! But if you check the way how it's done in this repo, it's not correct! 
Please read the issue again :)

**Comment by indiealexh** [comment]
What is not correct? I have seen no issue with the phalcon benchmark. To test it yourself just install phalcon.

**Comment by trentramseyer** [comment]
Yeah, not sure what he is going on about. You have a normal MVC call for Hello World like the rest.  (btw, when it will be Phalcon 3.x? )

**Comment by peshmerge** [comment]
You don't have any extra configuration(Like installing a C extension) to be able to test/run Laravel, Symfony or another framework. But for testing Phalcon you must first install some stuff and do a some configuration work. So when you want to run the benchmark you need to do that before benchmarking Phalcon, otherwise you will be testing/benchmarking requesting a 404-error page of Phalcon app.

Why I started this issue?! I did because I weren't aware of the fact that I need to install an extension for Phalcon before I can benchmark it. I forgot that because it wasn't mentioned on the guide/readme. 

I am not against Phalcon or I hate it. Totally not. It's just an advice to the creator of this benchmark to mention that to be able to benchmark phalcon, extra configuration is needed!

**Comment by indiealexh** [comment]
I don't believe you need to do any configuration... And your original message was not clear (or constructive) about the inconvenience of installing phalcon for yourself.

If you feel so strongly about it, then maybe produce a vagrant or docker image and share it?

**Comment by peshmerge** [comment]
Check the response of the creator of the benchmark! He admits that the benchmark is performed on an error page. 
I have to pass it for now, because I have exams. But I will come back soon 
Thanks for the advice of making a vagrant machine! Good idea 👍

**Comment by trentramseyer** [comment]
Takes less commands to install phalcon then it does laravel now.  3 tops on ubuntu without any composer needed. For 10 times the speed of yoyr app it is worth it.
