### ISSUE TITLE
Add a control case?

### ISSUE THREAD

**Issue by ChiperSoft** [kenjis/php-framework-benchmark#6]
I think the comparison could gain some useful context if you added a plain vanilla php file to the mix.  Since the goal is to see how much overhead is placed on a request, having a control case of no overhead at all gives a clear baseline for the capabilities of the testing hardware.

**Comment by kenjis** [comment]
I don't care the testing hardware. I encourage you to run benchmarks on your environments.

**Comment by ChiperSoft** [comment]
I'm not talking about testing hardware, I'm talking about scientific method.  You don't establish a baseline figure, so the numbers mean nothing. 

Is 1500 rps for phalcon good? We don't know, because we don't know how many requests per second the system could produce without any framework overhead at all.

If phalcon's peak memory is half a megabyte, how much of that is just the PHP runtime itself?  We don't know because there's no baseline.

You're not actually _measuring_ overhead. It doesn't matter whose system you test on when the tests don't have a control case.

**Comment by ATouhou** [comment]
Makes sense Chipersoft,  fork and push your changes to master? :-)

**Comment by kenjis** [comment]
If we know the baseline you say is, for example, 3000 rpm, then what do we know?
I don't know.
