### ISSUE TITLE
Command Not Found?

### ISSUE THREAD

**Issue by rohmanhm** [kenjis/php-framework-benchmark#65]
When I running `bash setup.sh` this message will show

```CLI
root@MHR-PC:/mnt/d/Web/GitHub/php-framework-benchmark# bash setup.sh
setup.sh: line 2: $'\r': command not found
setup.sh: line 27: syntax error near unexpected token `$'do\r''
'etup.sh: line 27: `do
```
Are you have solutions?

**Comment by macghriogair** [comment]
Did you run git clone on a Windows host? I had a similar issue with line endings and running dos2unix fixed it for me.

`vagrant$ dos2unix *.sh **/**.sh **/**/*.sh`

**Comment by rohmanhm** [comment]
Thanks. this is work fine
